### PR TITLE
WP checkbox options are integers

### PR DESCRIPTION
**Pull request by szepeviktor**
+Yoda

@tillkruss

### CODE REVIEW

**Comment by tillkruss** [comment]
If it's currently working and the check is already strict, wouldn't this break it?

**Comment by szepeviktor** [comment]
The thing is it is not working, at least in WP 4.9

**Comment by szepeviktor** [comment]
`1 !== '1'`

```bash
wp eval 'var_dump(get_option( "eae_notices", "0" ));'
```

**Comment by szepeviktor** [comment]
I've noticed: in v1.0.12 `string(1) "1"` in v1.0.14 `int(1)`
https://github.com/tillkruss/email-encoder/compare/1.0.12...1.0.14

**Comment by szepeviktor** [comment]
after disabling and enabling _Notices and promotions_ it changes from string(1) -> 0 -> int(1)

**Comment by tillkruss** [comment]
This might have caused it: 

https://github.com/tillkruss/email-encoder/commit/88e9cd7972283692e97f15a3c89495b05773b150#diff-7eec5692b9fd9edd9bf006170f5ce1ed

**Comment by tillkruss** [comment]
Let's switch to loose comparisons. I'm still in Laravel-mode.

**Comment by szepeviktor** [comment]
@tillkruss If you run WordPress maybe you'd like to run it faster ⚡️ https://github.com/szepeviktor/wordpress-autoloaded

**Comment by tillkruss** [comment]
Benchmarks?

**Comment by szepeviktor** [comment]
73% of number of files loaded: 133 instead of 182
88% of the runtime on CLI, not using OPcache

**Pull request merged**
